// This file was generated by RedwoodJS
import AboutPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/AboutPage/AboutPage'
import FatalErrorPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const AboutPage: typeof AboutPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
}
