// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
}
