// This file was generated by RedwoodJS
import AboutPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/AboutPage/AboutPage'
import EditPostPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/EditPostPage/EditPostPage'
import FatalErrorPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/HomePage/HomePage'
import NewPostPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/NewPostPage/NewPostPage'
import NotFoundPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/NotFoundPage/NotFoundPage'
import PostPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/PostPage/PostPage'
import PostsPageType from '/Users/max/sync/code/js/redwood-test/web/src/pages/PostsPage/PostsPage'

declare global {
  const AboutPage: typeof AboutPageType
  const EditPostPage: typeof EditPostPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NewPostPage: typeof NewPostPageType
  const NotFoundPage: typeof NotFoundPageType
  const PostPage: typeof PostPageType
  const PostsPage: typeof PostsPageType
}
