// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './PostCell'
import type { FIND_POST_BY_ID, FIND_POST_BY_IDVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './PostCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FIND_POST_BY_ID | 'updating'
> & FIND_POST_BY_IDVariables

export default function (props: CellInputs): ReturnType<SuccessType>
